language: python

jobs:
  include:
    - language: python
      python: 3.7
      script:
      - Backend/run_test.sh

    - language: java
      env: 
      - MYSQL_PASSWORD="test"
      - AES_SECRET_KEY="test"
      script:
      - cd Middleware && mvn test  
